name: deploy-to-okteto

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  setup-context:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: update config
        run: |
          sed -i 's/__PREFIX_URL__/${{ secrets.OKTETO_URL }}/' base/pref.yml

      - name: deploy
        uses: docker://okteto/okteto
        with:
          entrypoint: okteto
          args: deploy --namespace ${{ secrets.OKTETO_NAMESPACE }} --name subconverter --build
